### ISSUE TITLE
Update ConversationalAgent prompts in the hub

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/prompthub#40]
On hold till https://github.com/deepset-ai/haystack/pull/5065 is merged
```[tasklist]
### Tasks
- [ ] Let's handle this as well: https://github.com/deepset-ai/prompthub/issues/38
- [ ] https://github.com/deepset-ai/prompthub/issues/48
- [x] Add prompt links to tutorials, mainly the Agent ones
```
